name: isomorphic_git
description: A pure Dart implementation of Git - ported from isomorphic-git
version: 1.0.0
repository: https://github.com/kindkang2024/isomorphic-git

environment:
  sdk: ^3.8.0

dependencies:
  # Core dependencies
  crypto: ^3.0.0 # Or the latest version
  convert: ^3.1.1
  typed_data: ^1.3.2
  
  # HTTP support
  http: ^1.1.0
  universal_io: ^2.2.2
  
  # File system
  path: ^1.8.3
  
  # Utilities
  collection: ^1.18.0
  meta: ^1.11.0
  async: ^2.11.0
  archive: ^4.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
